#!/bin/bash
echo "INFORME SEU NÚMERO (DDD+NÚMERO)"
read NUMERO
echo "QUANTAS VEZES DESEJA REPETIR?"
read VEZES
for i in $(seq $VEZES);
do
data=$"msisdn=0$i$NUMERO&campid=4919b47c-f588-4e71-87e3-639b3af92e4d&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo ""
echo -e "\033[1;32mCONTAGEM:\033[1;37m$i"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mPARA INICIAR NOVAMENTE DIGITE: freemb\033[1;37m"
sleep 5
