#!/bin/bash
echo "INFORME SEU TOKEN"
reais TOKEN
echo "INFORME SEU NÚMERO (DDD+NÚMERO)"
read NUMERO
echo "QUANTAS VEZES DESEJA REPETIR?"
read VEZES
for i in $(seq $VEZES);
do
echo -e "\033[1;32mCONTAGEM:\033[1;37m$i"
echo ""
data=$"msisdn=0$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=1$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=2$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=3$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=4$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=5$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=6$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=7$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=8$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
data=$"msisdn=9$i$NUMERO&campid=4$TOKEN&opCode=VV" && site=$"http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
done
echo ""
echo -e "        \033[1;33m • \033[1;32mPROGRAMA FINALIZADO\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mPARA INICIAR NOVAMENTE DIGITE: freemb\033[1;37m"
sleep 5
